# Generated by Django 3.0.8 on 2020-07-28 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20200723_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='desc',
            field=models.CharField(default='This product has no description', max_length=3000),
        ),
    ]
